# получение датчиков
GET http://localhost:8000/api/sensors/
Content-Type: application/json

###

# создание датчика
POST http://localhost:8000/api/sensors/
Content-Type: application/json

{
  "name": "ESP323",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH http://localhost:8000/api/sensors/11/
Content-Type: application/json

{
  "description": "Перенес датчик в коридор"
}

###

# добавление измерения
POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 11,
  "temperature": 22.3
}

###

# получение информации по датчику
GET http://localhost:8000/api/sensors/11/
Content-Type: application/json
